# docker-compose automatically read variables from .env, no need to configure
services:
  api:
    build: .
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}:${COMMIT_TAG}
    container_name: ${DOCKER_CONTAINER}
    ports:
      # [Local Port]:[Docker Container Port]
      - "8000:8000"
    develop:
      watch:
        - path: ./server.py
          action: sync
          target: /app/server.py
       # - path: ./api/
       #   action: sync
       #   target: /app/api/
        - path: ./requirements.txt
          action: rebuild
    volumes:
      # Share the Google API credentials from your local machine
      - ./credentials.json:/app/credentials.json
      # Persist the login tokens so you don't have to re-authenticate
      - ./tokens:/app/tokens
